### PR TITLE
Extra benchmark for alt algh in math.hpp

### PR DESCRIPTION
**Pull request by Hexlord**
#### Description - What's this PR do?
Possible improvement of performance

#### Impacts/Risks of These Changes?
None

### CODE REVIEW

**Comment by Hexlord** [comment]
btw gitignore should not affect clang or gcc native environment and still can be expanded, yet makes it much easier to commit

**Comment by louis-langholtz** [comment]
Just an FYI on this...

I apologize for not having had even a compile ability check in place for the Benchmark application. Had I had one in place I believe it would have alerted us to this change not being able to compile as C++14 standard compliant code. The code failed to compile at least for me when I tried in C++14 mode with clang. I suspect it'd been fine meanwhile in C++17 mode. I changed the code you'd submitted to get something similar to compile and run for me.

I'm prioritizing getting the Benchmark application build and run into the Travis-CI system now so that we'll know next time that code compiles exactly as we intended.

**Comment by Hexlord** [comment]
Man, see, that is me not well familliar with C++11 and above, apologizing for that, you sure can change anything in order to make stuff better, I will try to follow the standards more strictly for such issues not to raise again. Love your work hon.

**Comment by louis-langholtz** [comment]
More update info...

I got the Benchmark application building now as part of the Travis-CI linux clang target. So now any new PRs we make involving code changes to the Benchmark application (or any/all of them) should actually be compile tested as part of the automated PR checks. I'm really pretty excited about it too! 😃 

This hopefully also makes it easier for anyone who wants to build and run the benchmark tests themselves to do so.

**Pull request merged**
