### PR TITLE
Math.hpp optimization

### PR DESCRIPTION
**Pull request by Hexlord**
Hard to tell, but looks like a better solution: avg of 5 movs, 2 bit cmps, 1 cmp, 2 subs, 1 abs (inacc estim)

### CODE REVIEW

**Comment by Hexlord** [comment]
hm, seems like it is impossible through constexpr, nevermind

**Comment by louis-langholtz** [comment]
Hi Hexlord. Thank you for working on a better solution!

I'm not sure `constexpr` is that useful for the `almost_equal` function. In the situations where it's most critical, I don't believe that the function would evaluate as actually being compile time computable. So not being through `constexpr` may not really matter.

I'm more concerned with whether or not the code would actually be faster. Hard to tell as you point out. I'm thinking it'd be a good candidate for a benchmark implementation though to compare the two implementations against each other.

**Comment by Hexlord** [comment]
Thanks for the attention, Louis, I am looking forward to form a commit for a new benchmark.

**Comment by louis-langholtz** [comment]
BTW... I whipped up some benchmark code just for the current implementation of the almost_equal function. I'd love it if you gave it a look. I was thinking this new code would be the basis then and you could trivially copy and paste it into 2 more new benchmarks then for the implementation you did.

Incidentally, I dislike that I've setup all of the benchmark tests within the same file (`Benchmark/BenchmarkMain.cpp`). I want to separate the benchmarks out into logical groups of benchmarks. Just haven't thought of a partitioning strategy that I'm particularly keen on yet for this.  I should probably put together build instructions and a cmake file for the existing benchmark application first anyway (and have issue #18 open at the moment for getting that done).

**Pull request closed without merging**
