### PR TITLE
resolve assertion issue when world steps after destroying any body with proxies.

### PR DESCRIPTION
**Pull request by pigpigyyy**
A better approach to fix invalid proxy id assertion issue.

### CODE REVIEW

**Comment by louis-langholtz** [comment]
I do like the "better way" commit better. Looks like @ninnghazad also like this commit.

Is there perhaps additional code you can come up with that preserves or increases the unit test coverage percentage?

**Comment by pigpigyyy** [comment]
```cpp
m_proxies.erase(std::remove_if(m_proxies.begin(), m_proxies.end(), [](ProxyId pid) {
        return pid == DynamicTree::GetInvalidSize();
}), m_proxies.end());
```
These codes make the coveralls say coverage decreased. But it is just a regular use of STL. I see there are similar uses in other PlayRho's codes also show coverage missed. The coverage tool has its own problem.

**Comment by ninnghazad** [comment]
hm, is inlining disabled for the test/coverage builds? maybe the lambdas get inlined away and cov can't track them.

**Comment by louis-langholtz** [comment]
Thank you @pigpigyyy for your effort on this! I did prefer these changes over what they applied to. Additionally, your having recognized the problem with `m_proxies` usage helped me identify a problem with `m_fixturesForProxies` usage as well.

I've now merged pull request #341 that seems to resolve both of these problems. The code in that pull request avoided placing the `DynamicTree::GetInvalidSize()` value into `m_proxies` to begin with and avoided the iterator invalidation that was occurring while iterating over `m_fixturesForProxies` (that was happening with `World::Step`) by removing the offending code that wasn't necessary anyway.

I wasn't able to come up with unit test code that detected the problem with `m_proxies` but if you pull the latest from master, please let me know if the assertion issue has gone away now and/or whether you see any new problems.

Thanks again!

**Pull request closed without merging**
